version: '3.9'

services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - backend-data:/data
      - ./backend:/app
    env_file:
      - backend/.env.example
    environment:
      ALABUGA_ENVIRONMENT=docker
    depends_on: []

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL=http://backend:8000
      NEXT_PUBLIC_DEMO_EMAIL=candidate@alabuga.space
      NEXT_PUBLIC_DEMO_PASSWORD=orbita123
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  backend-data:
