services:
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    volumes:
      - backend-data:/data
      - ./backend:/app
    env_file:
      - backend/.env
    depends_on: []
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    ports:
      - '3000:3000'
    env_file:
      - frontend/.env
    environment:
      NEXT_INTERNAL_API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge
